language: go
sudo: false
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
go:
- 1.2.2
- 1.3.1
- tip
install:
- make get
script:
- make test
after_success:
- make goveralls
env:
  global:
    secure: IWge0CPyTK73cgx67+8MD21u8auLqgsSXUwd2kwTNFv1ToefLRQr8tb3xtCcnZvUc2OpCUgak+iEj5IGSdVrfgnSmZ8zFpobU/m1jYZjGWTwUEG547FXeS75Z1GjbWR8H04PMqN+bwLVXaD/7eBKz/cyXa0PH8Q/3AmSFoJ4yfo=
